name: Auto Merge Upstream

on:
  schedule:
    - cron: "0 3 * * *"   # každý den ve 3:00 UTC
  workflow_dispatch:       # možnost spustit ručně

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout fork
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          fetch-depth: 0

      - name: Add upstream
        run: |
          git remote add upstream https://github.com/retromcorg/Project-Poseidon.git
          git fetch upstream

      - name: Merge upstream
        run: |
          git checkout main
          git merge upstream/main --no-edit || true

      - name: Push changes
        run: |
          git push origin main
