name: Auto Merge Upstream

on:
  schedule:
    - cron: "0 3 * * *"   # každý den ve 3:00 UTC
  workflow_dispatch:       # možnost spustit ručně

jobs:
  sync:
    runs-on: ubuntu-latest
    permissions:
      contents: read   # checkout nepotřebuje write, push jde přes PAT
    steps:
      - name: Checkout fork
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Add upstream
        run: |
          git remote add upstream https://github.com/retromcorg/Project-Poseidon.git || true
          git fetch upstream

      - name: Merge upstream
        run: |
          git checkout main
          git merge upstream/main --no-edit || true

      - name: Push changes using PAT
        env:
          PAT_TOKEN: ${{ secrets.PAT_TOKEN }}
        run: |
          git push https://x-access-token:$PAT_TOKEN@github.com/Grumpix/poseidon-patched.git main
