name: Release on Upstream Tag

on:
  workflow_dispatch:
  schedule:
    - cron: "0 4 * * *"   # každý den ve 4:00 UTC (po automerge)

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout fork
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          fetch-depth: 0

      - name: Add upstream
        run: |
          git remote add upstream https://github.com/retromcorg/Project-Poseidon.git
          git fetch --tags upstream

      - name: Check for new tag
        id: check
        run: |
          LATEST_UPSTREAM_TAG=$(git describe --tags `git rev-list --tags --max-count=1 upstream/main`)
          echo "latest_upstream_tag=$LATEST_UPSTREAM_TAG" >> $GITHUB_ENV
          if git rev-parse $LATEST_UPSTREAM_TAG >/dev/null 2>&1; then
            echo "tag_exists=true" >> $GITHUB_ENV
          else
            echo "tag_exists=false" >> $GITHUB_ENV
          fi

      - name: Create Release
        if: env.tag_exists == 'true'
        uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{ env.latest_upstream_tag }}
          name: Release ${{ env.latest_upstream_tag }}
          body: |
            Automated release based on upstream tag `${{ env.latest_upstream_tag }}`.
            Includes local patches (suppressed Bad packet id / Protocol error logging).
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
